services:
  hello:
    build: .
    container_name: hello-synology
    restart: unless-stopped

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
