"""Compatibility imports for the shared speech-transcription utilities."""

from info_triage.extractors.media.transcription import (
    BACKEND_CHOICES,
    FASTER_WHISPER_MODEL_REPOS,
    LEGACY_TRANSCRIPTION_BACKEND_ENV,
    LEGACY_TRANSCRIPTION_MODEL_ENV,
    LEGACY_TRANSCRIPTION_THREAD_ENV,
    MLX_MODEL_REPOS,
    MODEL_CHOICES,
    TRANSCRIPTION_BACKEND_ENV,
    TRANSCRIPTION_MODEL_ENV,
    TRANSCRIPTION_THREAD_ENV,
    FasterWhisperTranscriber,
    MLXWhisperTranscriber,
    Transcriber,
    TranscriptResult,
    TranscriptSegment,
    download_faster_whisper_model,
    has_audio_stream,
    make_transcriber,
    production_defaults,
    resolve_backend_and_model,
    resolve_transcription_threads,
    write_transcript_outputs,
)

__all__ = [
    "BACKEND_CHOICES",
    "FASTER_WHISPER_MODEL_REPOS",
    "LEGACY_TRANSCRIPTION_BACKEND_ENV",
    "LEGACY_TRANSCRIPTION_MODEL_ENV",
    "LEGACY_TRANSCRIPTION_THREAD_ENV",
    "MLX_MODEL_REPOS",
    "MODEL_CHOICES",
    "TRANSCRIPTION_BACKEND_ENV",
    "TRANSCRIPTION_MODEL_ENV",
    "TRANSCRIPTION_THREAD_ENV",
    "FasterWhisperTranscriber",
    "MLXWhisperTranscriber",
    "TranscriptResult",
    "TranscriptSegment",
    "Transcriber",
    "download_faster_whisper_model",
    "has_audio_stream",
    "make_transcriber",
    "production_defaults",
    "resolve_backend_and_model",
    "resolve_transcription_threads",
    "write_transcript_outputs",
]
