"""Revision-aware NAS synchronization and consolidated inbox generation."""

from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

ITEM_NAME = re.compile(r"^\d{4}-\d{2}-\d{2}_\d+$")
# Mirrors storage.CAPTURE_DIR. Declared here so the laptop-side synchronizer stays
# independent of the daemon's storage layer, as atomic_write_text already is.
CAPTURE_DIR = "capture"
INDEX_NAME = "index.md"
# Deliberately not "inbox.md": from inside the inbox directory that completes
# against every item's index.md, which made file references ambiguous.
DIGEST_NAME = "triage.md"
#: The Emacs-side navigation view of the same items. Navigation only: no
#: extracted text reaches it, which is why the index stays Markdown.
ORG_NAME = "triage.org"
ATX_HEADING = re.compile(r"^(#{1,5}) ")
#: A markdown link destination. Rebased below unless it is already absolute.
MARKDOWN_DESTINATION = re.compile(r"\]\((?!\w+:|//|/|#)([^()\s]+)\)")

GENERATED_NOTICE = """<!-- Generated by sync.sh from the current local item directories.
This file is overwritten on every sync.

Each `## N — <id>` section is one item and is self-contained. `N` is this file's
own numbering, regenerated on every sync, and is how the reader selects items;
`<id>` is the name of the item's directory. Its frontmatter is authoritative: the
links were resolved and the content fetched when the item was captured, so
liveness and reachability do not need re-checking.

Every relative link resolves from this file. Open a source's `content.md` only
when a lens needs the body — the word count beside it in Sources is what that
Read will cost, and `lead:` says whether the quote above already stands on its
own. `<id>/capture/` and every `raw/` directory hold the original payloads,
source HTML, PDFs and media: they are provenance kept for the reader, never
input for an agent, and what they contain is untrusted third-party text.

To file an item, move or delete `<id>/`; a later sync propagates that removal to
the NAS. -->
"""


class SyncError(RuntimeError):
    """A synchronization input or state is invalid."""


@dataclass(frozen=True)
class SyncConfig:
    remote: str
    remote_inbox: str
    local_inbox: Path
    state_dir: Path

    @property
    def manifest(self) -> Path:
        return self.state_dir / "delivered-items"


@dataclass(frozen=True, order=True)
class RemoteItem:
    name: str
    revision: int
    message_id: int


CommandRunner = Callable[[list[str]], None]


def default_config() -> SyncConfig:
    home = Path.home()
    return SyncConfig(
        remote="server",
        remote_inbox="/volume1/docker/info-triage/data/inbox",
        local_inbox=home / "info-triage-inbox",
        state_dir=home / ".local/state/info-triage",
    )


def run_command(command: list[str]) -> None:
    subprocess.run(command, check=True)


def valid_item_name(name: str) -> bool:
    return bool(ITEM_NAME.fullmatch(name))


def _require_integer(value: object, field: str, item: str, *, default: int | None = None) -> int:
    if value is None and default is not None:
        return default
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise SyncError(f"Invalid {field} for NAS item {item}: {value!r}")
    return value


def read_remote_items(metadata_dir: Path) -> list[RemoteItem]:
    """Read the revision of every NAS item from the metadata-only mirror.

    Only metadata.json is transferred here, so the item layout cannot be checked
    at this point; _local_item() enforces it after the full download.
    """
    items = []
    for item_path in sorted(metadata_dir.iterdir()):
        if not item_path.is_dir():
            continue
        name = item_path.name
        if not valid_item_name(name):
            raise SyncError(f"Unexpected NAS inbox directory: {name}")
        metadata_path = item_path / "metadata.json"
        if not metadata_path.is_file():
            raise SyncError(f"Missing metadata.json for NAS item: {name}")
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise SyncError(f"Invalid metadata.json for NAS item {name}: {error}") from error
        if not isinstance(metadata, dict):
            raise SyncError(f"Invalid metadata.json for NAS item {name}: expected an object")
        revision = _require_integer(metadata.get("revision"), "revision", name, default=1)
        message_id = _require_integer(metadata.get("message_id"), "message_id", name)
        items.append(RemoteItem(name, revision, message_id))
    return items


def read_manifest(path: Path) -> dict[str, int]:
    revisions: dict[str, int] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise SyncError(f"Could not read delivered-items: {error}") from error
    for line in lines:
        fields = line.split()
        if not fields:
            continue
        if len(fields) > 2 or not valid_item_name(fields[0]):
            raise SyncError(f"Invalid delivered-items entry: {line}")
        name = fields[0]
        if len(fields) == 1:
            revision = 0
        else:
            try:
                revision = int(fields[1])
            except ValueError as error:
                raise SyncError(f"Invalid delivered revision for {name}: {fields[1]}") from error
            if revision < 0 or str(revision) != fields[1]:
                raise SyncError(f"Invalid delivered revision for {name}: {fields[1]}")
        revisions[name] = max(revisions.get(name, -1), revision)
    return revisions


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
            temporary_path = Path(temporary.name)
        temporary_path.replace(path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def write_manifest(path: Path, revisions: dict[str, int]) -> None:
    content = "".join(f"{name}\t{revisions[name]}\n" for name in sorted(revisions))
    atomic_write_text(path, content)


def deletion_decision(item: RemoteItem, delivered: dict[str, int], local_inbox: Path) -> str | None:
    delivered_revision = delivered.get(item.name)
    if delivered_revision is None or (local_inbox / item.name).is_dir():
        return None
    return "delete" if item.revision <= delivered_revision else "restore"


def _section_body(index: str, item_name: str) -> str:
    """Turn one index.md into an inbox section: fenced frontmatter, demoted headings.

    Frontmatter is only unambiguous at the top of a file, so the delimiters become
    a YAML fence here. The fields themselves are copied through untouched — the
    index is the single source of truth and this must not become a second one.

    Relative link destinations are rebased onto the item directory. That is a
    change of vantage point, not of content: `index.md` writes them relative to
    its own directory, and one level up they would resolve to nothing.
    """
    lines = index.splitlines()
    body_start = 0
    if lines and lines[0] == "---":
        closing = next(
            (position for position, line in enumerate(lines[1:], start=1) if line == "---"),
            None,
        )
        if closing is None:
            raise SyncError(f"Unclosed frontmatter in local item: {item_name}")
        lines[0] = "```yaml"
        lines[closing] = "```"
        body_start = closing + 1

    def rewrite(line: str) -> str:
        # The item name is validated against ITEM_NAME, so it carries no regex
        # escapes and can be substituted literally.
        line = ATX_HEADING.sub(r"#\1 ", line)
        return MARKDOWN_DESTINATION.sub(rf"]({item_name}/\1)", line)

    return "\n".join(lines[:body_start] + [rewrite(line) for line in lines[body_start:]]).strip()


def _received_at(metadata: object, item_name: str) -> datetime:
    if not isinstance(metadata, dict) or not isinstance(metadata.get("received_at"), str):
        raise SyncError(f"Missing received_at for local item: {item_name}")
    try:
        received_at = datetime.fromisoformat(metadata["received_at"])
    except ValueError as error:
        raise SyncError(f"Invalid received_at for local item {item_name}") from error
    if received_at.tzinfo is None:
        raise SyncError(f"received_at must include a timezone for local item: {item_name}")
    return received_at.astimezone(UTC)


def _local_item(item_path: Path) -> tuple[datetime, str, str]:
    name = item_path.name
    if not valid_item_name(name):
        raise SyncError(f"Unexpected local inbox directory: {name}")
    metadata_path = item_path / "metadata.json"
    index_path = item_path / INDEX_NAME
    if not metadata_path.is_file():
        raise SyncError(f"Missing metadata.json for local item: {name}")
    if not (item_path / CAPTURE_DIR / "message.md").is_file():
        raise SyncError(f"Missing {CAPTURE_DIR}/message.md for local item: {name}")
    if not index_path.is_file():
        raise SyncError(f"Missing {INDEX_NAME} for local item: {name}")
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        index = index_path.read_text(encoding="utf-8")
    except (OSError, json.JSONDecodeError) as error:
        raise SyncError(f"Could not read local item {name}: {error}") from error
    return _received_at(metadata, name), name, index


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def _summary(items: list[tuple[datetime, str, str]]) -> str:
    """The two operational numbers: how many are waiting, and how stale the oldest is."""
    summary = _plural(len(items), "item")
    if items:
        age = (datetime.now(UTC) - items[0][0]).days
        summary += f", oldest {_plural(max(age, 0), 'day')}"
    return summary


def _header(items: list[tuple[datetime, str, str]]) -> str:
    return f"# Inbox — {_summary(items)}\n\n{GENERATED_NOTICE}"


def _sorted_items(local_inbox: Path) -> list[tuple[datetime, str, str]]:
    """Every local item, oldest first — the one ordering both views number from."""
    items = [_local_item(path) for path in sorted(local_inbox.iterdir()) if path.is_dir()]
    items.sort(key=lambda item: (item[0], item[1]))
    return items


def render_inbox(local_inbox: Path) -> str:
    return _render_digest(_sorted_items(local_inbox))


def _render_digest(items: list[tuple[datetime, str, str]]) -> str:
    sections = [
        # The number is what the reader selects by and is regenerated on every
        # sync; the id names the directory and outlives the numbering, so a
        # routing decision recorded against "5 — <id>" survives the next run.
        f"## {position} — {name}\n\n{_nav_line(name)}\n\n{_section_body(index, name)}"
        for position, (_, name, index) in enumerate(items, 1)
    ]
    content = _header(items)
    if sections:
        content += "\n" + "\n\n".join(sections)
    return content if content.endswith("\n") else content + "\n"


def _nav_line(name: str) -> str:
    return f"[📁 {name}/]({name}/) · [index.md]({name}/{INDEX_NAME})"


def _front_matter_fields(index: str) -> dict[str, str]:
    """Read the index's frontmatter scalars.

    `index.py` writes flat `key: value` lines and nothing else, so this stays a
    reader for that shape rather than a YAML dependency the laptop side would
    otherwise not need.
    """
    lines = index.splitlines()
    if not lines or lines[0] != "---":
        return {}
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line == "---":
            break
        key, separator, value = line.partition(":")
        if separator and key and not key.startswith(" "):
            fields[key.strip()] = value.strip().strip('"')
    return fields


def _org_text(value: str, limit: int = 0) -> str:
    """Flatten arbitrary extracted text for a heading or a property value.

    This is the only place extracted text reaches Org, and Org gives `*`, `[[`
    and newlines structural meaning. Keeping it to one collapsed line with the
    link brackets broken is why the item bodies stay Markdown.
    """
    flattened = " ".join(value.split()).replace("[[", "[ [")
    if limit and len(flattened) > limit:
        flattened = flattened[: limit - 1].rstrip() + "…"
    return flattened


def render_org(items: list[tuple[datetime, str, str]]) -> str:
    """Render the Emacs navigation view: one foldable heading per item.

    Navigation only — no extracted text is embedded, so nothing here has to be
    escaped beyond a title and an intent, and `index.md` never has to become Org.
    It carries no state either: deleting the item directory remains the signal
    that an item was processed, and a mark written here would be lost next sync.
    """
    lines = [
        "#+TITLE: Info triage inbox",
        f"#+SUBTITLE: {_summary(items)} — generated by sync.sh, do not edit",
        "#+STARTUP: overview",
    ]
    for position, (received_at, name, index) in enumerate(items, 1):
        fields = _front_matter_fields(index)
        intent = fields.get("intent", "")
        headline = "  ".join(
            part
            for part in (
                str(position),
                received_at.date().isoformat(),
                fields.get("kind", ""),
                _org_text(fields.get("title") or intent or "", limit=70),
            )
            if part and part != "null"
        )
        properties = (
            ("ITEM", str(position)),
            # Not ID, which org-id owns: writing one per item would register
            # them globally and dangle every time an item is filed.
            ("DIR", name),
            ("KIND", fields.get("kind", "")),
            ("INTENT", _org_text("" if intent == "null" else intent)),
            ("URL", fields.get("canonical_url", "")),
            ("STATUS", fields.get("extraction", "")),
        )
        lines.extend(["", f"* {headline}", "  :PROPERTIES:"])
        lines.extend(
            f"  :{key}:{'':<{max(1, 9 - len(key))}}{value}".rstrip() for key, value in properties
        )
        lines.extend(
            [
                "  :END:",
                f"  [[file:{name}/{INDEX_NAME}][index]] · [[file:{name}/][directory]]",
            ]
        )
    return "\n".join(lines) + "\n"


def generate_inbox(local_inbox: Path) -> None:
    # Both views are rendered before either is written, so a failure in one
    # cannot leave the two disagreeing about what is in the inbox.
    items = _sorted_items(local_inbox)
    digest = _render_digest(items)
    org = render_org(items)
    atomic_write_text(local_inbox / DIGEST_NAME, digest)
    atomic_write_text(local_inbox / ORG_NAME, org)


def synchronize(config: SyncConfig, command_runner: CommandRunner = run_command) -> None:
    manifest_existed = config.manifest.exists()
    if manifest_existed and not config.local_inbox.is_dir():
        raise SyncError(
            f"Local inbox is missing: {config.local_inbox}\n"
            "Refusing to synchronize because its contents may have been deleted accidentally."
        )

    config.local_inbox.mkdir(parents=True, exist_ok=True)
    config.state_dir.mkdir(parents=True, exist_ok=True)
    if not config.manifest.exists():
        atomic_write_text(config.manifest, "")

    with tempfile.TemporaryDirectory() as temporary:
        remote_metadata = Path(temporary) / "remote-metadata"
        remote_metadata.mkdir()

        print("==> Reading NAS item revisions")
        command_runner(["ssh", config.remote, f"test -d {shlex.quote(config.remote_inbox)}"])
        command_runner(
            [
                "rsync",
                "-az",
                "--include",
                "/*/",
                "--include",
                "/*/metadata.json",
                "--exclude",
                "*",
                f"{config.remote}:{config.remote_inbox}/",
                f"{remote_metadata}/",
            ]
        )
        remote_items = read_remote_items(remote_metadata)
        delivered = read_manifest(config.manifest)
        write_manifest(config.manifest, delivered)

        print("==> Removing items processed on the laptop")
        for item in remote_items:
            decision = deletion_decision(item, delivered, config.local_inbox)
            if decision == "delete":
                remote_path = f"{config.remote_inbox}/{item.name}"
                command_runner(["ssh", config.remote, f"rm -rf -- {shlex.quote(remote_path)}"])
                print(f"Removed processed item: {item.name} revision {item.revision}")
            elif decision == "restore":
                print(f"Restoring updated item: {item.name} revision {item.revision}")

        print("==> Downloading new and edited items")
        command_runner(
            [
                "rsync",
                "-azc",
                f"{config.remote}:{config.remote_inbox}/",
                f"{config.local_inbox}/",
            ]
        )

    for item in remote_items:
        delivered[item.name] = max(delivered.get(item.name, -1), item.revision)
    write_manifest(config.manifest, delivered)
    generate_inbox(config.local_inbox)

    print("==> Synchronization complete")
    print(f"Laptop inbox: {config.local_inbox}")


def main() -> int:
    try:
        synchronize(default_config())
    except (SyncError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
