"""Revision-aware NAS synchronization and consolidated inbox generation."""

from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

ITEM_NAME = re.compile(r"^\d{4}-\d{2}-\d{2}_\d+$")
# Mirrors storage.CAPTURE_DIR. Declared here so the laptop-side synchronizer stays
# independent of the daemon's storage layer, as atomic_write_text already is.
CAPTURE_DIR = "capture"
FRONT_MATTER_FIELD = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):[ \t]*(.*)$")

GENERATED_HEADER = """# Inbox

<!-- Generated by sync.sh from the current local item directories.
This file is overwritten on every sync. Each section contains user-facing
metadata followed by captured content. To acknowledge an item, move or delete
its linked directory; a later sync propagates that removal to the NAS. -->
"""


class SyncError(RuntimeError):
    """A synchronization input or state is invalid."""


@dataclass(frozen=True)
class SyncConfig:
    remote: str
    remote_inbox: str
    local_inbox: Path
    state_dir: Path

    @property
    def manifest(self) -> Path:
        return self.state_dir / "delivered-items"


@dataclass(frozen=True, order=True)
class RemoteItem:
    name: str
    revision: int
    message_id: int


CommandRunner = Callable[[list[str]], None]


def default_config() -> SyncConfig:
    home = Path.home()
    return SyncConfig(
        remote="server",
        remote_inbox="/volume1/docker/info-triage/data/inbox",
        local_inbox=home / "info-triage-inbox",
        state_dir=home / ".local/state/info-triage",
    )


def run_command(command: list[str]) -> None:
    subprocess.run(command, check=True)


def valid_item_name(name: str) -> bool:
    return bool(ITEM_NAME.fullmatch(name))


def _require_integer(value: object, field: str, item: str, *, default: int | None = None) -> int:
    if value is None and default is not None:
        return default
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise SyncError(f"Invalid {field} for NAS item {item}: {value!r}")
    return value


def read_remote_items(metadata_dir: Path) -> list[RemoteItem]:
    """Read the revision of every NAS item from the metadata-only mirror.

    Only metadata.json is transferred here, so the item layout cannot be checked
    at this point; _local_item() enforces it after the full download.
    """
    items = []
    for item_path in sorted(metadata_dir.iterdir()):
        if not item_path.is_dir():
            continue
        name = item_path.name
        if not valid_item_name(name):
            raise SyncError(f"Unexpected NAS inbox directory: {name}")
        metadata_path = item_path / "metadata.json"
        if not metadata_path.is_file():
            raise SyncError(f"Missing metadata.json for NAS item: {name}")
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise SyncError(f"Invalid metadata.json for NAS item {name}: {error}") from error
        if not isinstance(metadata, dict):
            raise SyncError(f"Invalid metadata.json for NAS item {name}: expected an object")
        revision = _require_integer(metadata.get("revision"), "revision", name, default=1)
        message_id = _require_integer(metadata.get("message_id"), "message_id", name)
        items.append(RemoteItem(name, revision, message_id))
    return items


def read_manifest(path: Path) -> dict[str, int]:
    revisions: dict[str, int] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise SyncError(f"Could not read delivered-items: {error}") from error
    for line in lines:
        fields = line.split()
        if not fields:
            continue
        if len(fields) > 2 or not valid_item_name(fields[0]):
            raise SyncError(f"Invalid delivered-items entry: {line}")
        name = fields[0]
        if len(fields) == 1:
            revision = 0
        else:
            try:
                revision = int(fields[1])
            except ValueError as error:
                raise SyncError(f"Invalid delivered revision for {name}: {fields[1]}") from error
            if revision < 0 or str(revision) != fields[1]:
                raise SyncError(f"Invalid delivered revision for {name}: {fields[1]}")
        revisions[name] = max(revisions.get(name, -1), revision)
    return revisions


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
            temporary_path = Path(temporary.name)
        temporary_path.replace(path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def write_manifest(path: Path, revisions: dict[str, int]) -> None:
    content = "".join(f"{name}\t{revisions[name]}\n" for name in sorted(revisions))
    atomic_write_text(path, content)


def deletion_decision(item: RemoteItem, delivered: dict[str, int], local_inbox: Path) -> str | None:
    delivered_revision = delivered.get(item.name)
    if delivered_revision is None or (local_inbox / item.name).is_dir():
        return None
    return "delete" if item.revision <= delivered_revision else "restore"


def _front_matter(message: str, item_name: str) -> tuple[list[tuple[str, str]], str]:
    lines = message.splitlines(keepends=True)
    if not lines or lines[0].rstrip("\r\n") != "---":
        return [], message
    closing_index = next(
        (index for index, line in enumerate(lines[1:], start=1) if line.rstrip("\r\n") == "---"),
        None,
    )
    if closing_index is None:
        raise SyncError(f"Unclosed front matter in local item: {item_name}")
    fields = []
    seen = set()
    for line in lines[1:closing_index]:
        raw_line = line.rstrip("\r\n")
        match = FRONT_MATTER_FIELD.fullmatch(raw_line)
        if not match:
            raise SyncError(f"Invalid front matter in local item {item_name}: {raw_line!r}")
        key, value = match.groups()
        if key in seen:
            raise SyncError(f"Duplicate front-matter field in local item {item_name}: {key}")
        seen.add(key)
        fields.append((key, value))
    return fields, "".join(lines[closing_index + 1 :])


def _code_span(value: str) -> str:
    longest_run = max((len(match.group()) for match in re.finditer(r"`+", value)), default=0)
    delimiter = "`" * (longest_run + 1)
    padding = " " if value.startswith("`") or value.endswith("`") else ""
    return f"{delimiter}{padding}{value}{padding}{delimiter}"


def _field_label(key: str) -> str:
    return key.replace("_", " ").replace("-", " ").capitalize()


def _received_at(metadata: object, item_name: str) -> datetime:
    if not isinstance(metadata, dict) or not isinstance(metadata.get("received_at"), str):
        raise SyncError(f"Missing received_at for local item: {item_name}")
    try:
        received_at = datetime.fromisoformat(metadata["received_at"])
    except ValueError as error:
        raise SyncError(f"Invalid received_at for local item {item_name}") from error
    if received_at.tzinfo is None:
        raise SyncError(f"received_at must include a timezone for local item: {item_name}")
    return received_at.astimezone(UTC)


def _local_item(item_path: Path) -> tuple[datetime, str, list[tuple[str, str]], str]:
    name = item_path.name
    if not valid_item_name(name):
        raise SyncError(f"Unexpected local inbox directory: {name}")
    metadata_path = item_path / "metadata.json"
    message_path = item_path / CAPTURE_DIR / "message.md"
    if not metadata_path.is_file():
        raise SyncError(f"Missing metadata.json for local item: {name}")
    if not message_path.is_file():
        raise SyncError(f"Missing {CAPTURE_DIR}/message.md for local item: {name}")
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        message = message_path.read_text(encoding="utf-8")
    except (OSError, json.JSONDecodeError) as error:
        raise SyncError(f"Could not read local item {name}: {error}") from error
    received_at = _received_at(metadata, name)
    fields, body = _front_matter(message, name)
    return received_at, name, fields, body


def render_inbox(local_inbox: Path) -> str:
    items = []
    for path in sorted(local_inbox.iterdir()):
        if path.is_dir():
            items.append(_local_item(path))
    items.sort(key=lambda item: (item[0], item[1]))

    sections = []
    for received_at, name, fields, body in items:
        timestamp = received_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        metadata_lines = ["> **Metadata**", ">"]
        metadata_lines.extend(
            f"> - {_field_label(key)}: {_code_span(value)}" for key, value in fields
        )
        metadata_lines.append(f"> - Item directory: [open](./{name}/)")
        prefix = f"## {timestamp}\n\n" + "\n".join(metadata_lines) + "\n"
        if body and not body.startswith(("\n", "\r")):
            prefix += "\n"
        sections.append(prefix + body)

    if not sections:
        return GENERATED_HEADER
    content = GENERATED_HEADER + "\n" + "\n\n".join(sections)
    return content if content.endswith("\n") else content + "\n"


def generate_inbox(local_inbox: Path) -> None:
    content = render_inbox(local_inbox)
    atomic_write_text(local_inbox / "inbox.md", content)


def synchronize(config: SyncConfig, command_runner: CommandRunner = run_command) -> None:
    manifest_existed = config.manifest.exists()
    if manifest_existed and not config.local_inbox.is_dir():
        raise SyncError(
            f"Local inbox is missing: {config.local_inbox}\n"
            "Refusing to synchronize because its contents may have been deleted accidentally."
        )

    config.local_inbox.mkdir(parents=True, exist_ok=True)
    config.state_dir.mkdir(parents=True, exist_ok=True)
    if not config.manifest.exists():
        atomic_write_text(config.manifest, "")

    with tempfile.TemporaryDirectory() as temporary:
        remote_metadata = Path(temporary) / "remote-metadata"
        remote_metadata.mkdir()

        print("==> Reading NAS item revisions")
        command_runner(["ssh", config.remote, f"test -d {shlex.quote(config.remote_inbox)}"])
        command_runner(
            [
                "rsync",
                "-az",
                "--include",
                "/*/",
                "--include",
                "/*/metadata.json",
                "--exclude",
                "*",
                f"{config.remote}:{config.remote_inbox}/",
                f"{remote_metadata}/",
            ]
        )
        remote_items = read_remote_items(remote_metadata)
        delivered = read_manifest(config.manifest)
        write_manifest(config.manifest, delivered)

        print("==> Removing items processed on the laptop")
        for item in remote_items:
            decision = deletion_decision(item, delivered, config.local_inbox)
            if decision == "delete":
                remote_path = f"{config.remote_inbox}/{item.name}"
                command_runner(["ssh", config.remote, f"rm -rf -- {shlex.quote(remote_path)}"])
                print(f"Removed processed item: {item.name} revision {item.revision}")
            elif decision == "restore":
                print(f"Restoring updated item: {item.name} revision {item.revision}")

        print("==> Downloading new and edited items")
        command_runner(
            [
                "rsync",
                "-azc",
                f"{config.remote}:{config.remote_inbox}/",
                f"{config.local_inbox}/",
            ]
        )

    for item in remote_items:
        delivered[item.name] = max(delivered.get(item.name, -1), item.revision)
    write_manifest(config.manifest, delivered)
    generate_inbox(config.local_inbox)

    print("==> Synchronization complete")
    print(f"Laptop inbox: {config.local_inbox}")


def main() -> int:
    try:
        synchronize(default_config())
    except (SyncError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
