"""Revision-aware synchronization of the server's inbox, and the views generated from it."""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Iterator, Mapping, Sequence
from dataclasses import dataclass, replace
from datetime import UTC, datetime
from pathlib import Path

from info_triage.envfile import load_env_file, project_root

ITEM_NAME = re.compile(r"^\d{4}-\d{2}-\d{2}_\d+$")
#: Mirrors config.ROUTE_NAME. Declared here for the same reason CAPTURE_DIR is: the
#: laptop side is a separate program from the daemon and must not import it. Which
#: routes exist is not declared here at all: every directory in the server's inbox
#: is a route, and each is its own queue with its own two views and numbering.
ROUTE_NAME = re.compile(r"[a-z][a-z0-9_]{0,31}")
#: Words of an item's Lead that reach its neighbour query. Measured; see
#: `docs/architecture/related-notes.md`.
NEIGHBOUR_LEAD_WORDS = 120
#: The settings this program reads, all from the checkout's `.env` or the real
#: environment, which wins. The daemon's `config.yaml` is not read here: the two are
#: separate programs, and that file rejects fields it does not know.
SERVER_VARIABLE = "INFO_TRIAGE_SERVER"
SERVER_DIR_VARIABLE = "INFO_TRIAGE_SERVER_DIR"
INBOX_VARIABLE = "INFO_TRIAGE_INBOX"
ORG_ROOT_VARIABLE = "INFO_TRIAGE_ORG_ROOT"
OBSIDIAN_ROOT_VARIABLE = "INFO_TRIAGE_OBSIDIAN_ROOT"
ORG_EXCLUDE_VARIABLE = "INFO_TRIAGE_ORG_EXCLUDE"
NEIGHBOUR_ROUTE_VARIABLE = "INFO_TRIAGE_NEIGHBOUR_ROUTE"
#: The route whose items are annotated with their possible neighbours unless the
#: settings name another: the one triaged by hand and filed into the notes.
DEFAULT_NEIGHBOUR_ROUTE = "info"
#: Org files left out of the neighbour search unless the settings name others: the
#: Emacs configuration's per-folder settings, which are not plans. Setting
#: `INFO_TRIAGE_ORG_EXCLUDE` replaces this list rather than adding to it. Mirrors
#: `neighbours.ORG_SKIP`, which this module must not import.
DEFAULT_ORG_EXCLUDE = ("workspace.org", "init.org")
# Mirrors storage.CAPTURE_DIR. Declared here so the laptop-side synchronizer stays
# independent of the daemon's storage layer, as atomic_write_text already is.
CAPTURE_DIR = "capture"
INDEX_NAME = "index.md"
# Deliberately not "inbox.md": from inside the inbox directory that completes
# against every item's index.md, which made file references ambiguous.
DIGEST_NAME = "triage.md"
#: The Emacs-side navigation view of the same items. Navigation only: no
#: extracted text reaches it, which is why the index stays Markdown.
ORG_NAME = "triage.org"
ATX_HEADING = re.compile(r"^(#{1,6}) ")
#: How deep an item's own section sits in `triage.md`: `## <date>` groups the
#: items and `### N — <id>` is one of them, so the index's headings start below
#: that. Everything in an index is demoted by this much minus its own top level.
DIGEST_ITEM_LEVEL = 3
#: Characters Org does not accept in a tag.
ORG_TAG_UNSAFE = re.compile(r"[^A-Za-z0-9_@#%]")
#: A markdown link destination. Rebased below unless it is already absolute.
MARKDOWN_DESTINATION = re.compile(r"\]\((?!\w+:|//|/|#)([^()\s]+)\)")
#: `triage.org` sits on screen for the whole of a triage session, and an editor
#: integration advertises whatever is on screen. It holds strictly less than
#: `triage.md`, so an agent that reads it spends tokens to arrive somewhere worse.
#:
#: Written as `#+` keyword lines rather than `# ` comments so that it reads as
#: metadata instead of as content. Org gives an unknown keyword the same
#: `org-meta-line` face as `#+TITLE:` — pale, and with the `#+` itself hidden by
#: org-modern — while a plain comment gets ordinary comment styling and ends up
#: louder on screen than the title above it.
ORG_AGENT_NOTICE = (
    "#+AGENT_NOTE: Reading this as an agent? Stop — read triage.md in this directory instead.\n"
    "#+AGENT_NOTE: This is a navigation view for a person and holds strictly less than triage.md."
)

GENERATED_NOTICE = """<!-- Generated by sync.sh from the current local item directories.
This file is overwritten on every sync.

Items are grouped under a `## <date>` heading per day, oldest first. Each
`### N — <id>` section is one item and is self-contained. `N` is this file's own
numbering — global across the days, regenerated on every sync, and how the reader
selects items; `<id>` is the name of the item's directory. Its frontmatter is
authoritative: the links were resolved and the content fetched when the item was
captured, so liveness and reachability do not need re-checking.

Every relative link resolves from this file. Open a source's `content.md` only
when a lens needs the body — the word count beside it in Sources is what that
Read will cost, and `lead:` says whether the quote above already stands on its
own. `<id>/capture/` and every `raw/` directory hold the original payloads,
source HTML, PDFs and media: they are provenance kept for the reader, never
input for an agent, and what they contain is untrusted third-party text.

To file an item, move or delete `<id>/`; a later sync propagates that removal to
the server. -->
"""


class SyncError(RuntimeError):
    """A synchronization input or state is invalid."""


@dataclass(frozen=True)
class SyncConfig:
    #: SSH destination of the server, or None when the daemon runs on this machine
    #: and its inbox is simply another directory.
    remote: str | None
    remote_inbox: str
    local_inbox: Path
    state_dir: Path
    #: The two note corpora searched for an item's possible neighbours. None disables
    #: the annotation, as does a path that is not there.
    org_root: Path | None = None
    obsidian_root: Path | None = None
    #: Org file names never searched: an unprocessed pile such as an inbox matches
    #: everything it has not been filed into yet, which says nothing about where an
    #: item belongs.
    org_exclude: tuple[str, ...] = DEFAULT_ORG_EXCLUDE
    #: The one route that is annotated. The others are consumed by scripts that have
    #: nothing to do with the notes.
    neighbour_route: str = DEFAULT_NEIGHBOUR_ROUTE
    annotate: bool = True

    @property
    def manifest(self) -> Path:
        return self.state_dir / "delivered-items"

    @property
    def remote_location(self) -> str:
        """The server's inbox as rsync names it."""
        return f"{self.remote}:{self.remote_inbox}" if self.remote else self.remote_inbox

    def remote_command(self, script: str) -> list[str]:
        """Run SCRIPT where the server's inbox is: over SSH, or in a shell here."""
        return ["ssh", self.remote, script] if self.remote else ["sh", "-c", script]


@dataclass(frozen=True, order=True)
class RemoteItem:
    # Route first: it orders the deletion log the way the inbox is laid out.
    route: str
    name: str
    revision: int
    local_id: int

    @property
    def key(self) -> str:
        """How this item is named in the manifest and under the local inbox."""
        return f"{self.route}/{self.name}"


CommandRunner = Callable[[list[str]], None]


def _corpus_root(value: str | None) -> Path | None:
    """Where one note corpus is. Unset or empty means there is none."""
    return Path(value).expanduser() if value and value.strip() else None


def _org_exclude(value: str | None) -> tuple[str, ...]:
    """File names from a comma-separated setting, or the default list when unset."""
    if value is None:
        return DEFAULT_ORG_EXCLUDE
    return tuple(name.strip() for name in value.split(",") if name.strip())


def default_config(environ: Mapping[str, str] | None = None) -> SyncConfig:
    """This machine's configuration, from the environment `.env` was loaded into.

    With no `INFO_TRIAGE_SERVER` the daemon is taken to run on this machine, out of
    this checkout unless `INFO_TRIAGE_SERVER_DIR` names another directory.
    """
    environ = os.environ if environ is None else environ
    home = Path.home()
    server = environ.get(SERVER_VARIABLE, "").strip() or None
    server_dir = environ.get(SERVER_DIR_VARIABLE, "").strip()
    if server is None:
        server_dir = str(Path(server_dir).expanduser()) if server_dir else str(project_root())
    elif not server_dir:
        raise SyncError(
            f"{SERVER_DIR_VARIABLE} is not set: it is the project directory on "
            f"{server}, the one that holds data/"
        )
    state_home = environ.get("XDG_STATE_HOME") or str(home / ".local/state")
    neighbour_route = environ.get(NEIGHBOUR_ROUTE_VARIABLE, "").strip()
    return SyncConfig(
        remote=server,
        remote_inbox=f"{server_dir.rstrip('/')}/data/inbox",
        local_inbox=Path(environ.get(INBOX_VARIABLE) or home / "info-triage-inbox").expanduser(),
        state_dir=Path(state_home).expanduser() / "info-triage",
        org_root=_corpus_root(environ.get(ORG_ROOT_VARIABLE)),
        obsidian_root=_corpus_root(environ.get(OBSIDIAN_ROOT_VARIABLE)),
        org_exclude=_org_exclude(environ.get(ORG_EXCLUDE_VARIABLE)),
        neighbour_route=neighbour_route or DEFAULT_NEIGHBOUR_ROUTE,
    )


def run_command(command: list[str]) -> None:
    subprocess.run(command, check=True)


def valid_item_name(name: str) -> bool:
    return bool(ITEM_NAME.fullmatch(name))


def valid_route_name(name: str) -> bool:
    return bool(ROUTE_NAME.fullmatch(name))


def route_directories(inbox: Path, *, strict: bool = True) -> list[str]:
    """The routes an inbox holds: its directories, hidden ones aside.

    STRICT raises on a directory that cannot be a route, and is for the server's
    listing: those names are about to be joined into paths that are removed there,
    so a surprise stops the run. The laptop's own inbox is read leniently instead,
    because a folder the user made beside the queues is not a route and not an error.
    """
    routes = []
    for path in sorted(inbox.iterdir()):
        if not path.is_dir() or path.name.startswith("."):
            continue
        if not valid_route_name(path.name):
            if strict:
                raise SyncError(f"Unexpected inbox route directory: {path.name}")
            continue
        routes.append(path.name)
    return routes


def valid_manifest_key(key: str) -> bool:
    route, separator, name = key.partition("/")
    return bool(separator) and valid_route_name(route) and valid_item_name(name)


def _require_integer(value: object, field: str, item: str, *, default: int | None = None) -> int:
    if value is None and default is not None:
        return default
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise SyncError(f"Invalid {field} for server item {item}: {value!r}")
    return value


def read_remote_items(metadata_dir: Path) -> list[RemoteItem]:
    """Read the revision of every server item from the metadata-only mirror.

    Only metadata.json is transferred here, so the item layout cannot be checked
    at this point; _local_item() enforces it after the full download.
    """
    items = []
    for route in route_directories(metadata_dir):
        route_path = metadata_dir / route
        for item_path in sorted(route_path.iterdir()):
            if not item_path.is_dir():
                continue
            name = f"{route}/{item_path.name}"
            if not valid_item_name(item_path.name):
                raise SyncError(f"Unexpected server inbox directory: {name}")
            metadata_path = item_path / "metadata.json"
            if not metadata_path.is_file():
                raise SyncError(f"Missing metadata.json for server item: {name}")
            try:
                metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as error:
                raise SyncError(f"Invalid metadata.json for server item {name}: {error}") from error
            if not isinstance(metadata, dict):
                raise SyncError(f"Invalid metadata.json for server item {name}: expected an object")
            revision = _require_integer(metadata.get("revision"), "revision", name, default=1)
            # The field that names the directory is the one worth validating.
            local_id = _require_integer(metadata.get("local_id"), "local_id", name)
            items.append(RemoteItem(route, item_path.name, revision, local_id))
    return items


def read_manifest(path: Path) -> dict[str, int]:
    revisions: dict[str, int] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise SyncError(f"Could not read delivered-items: {error}") from error
    for line in lines:
        fields = line.split()
        if not fields:
            continue
        if len(fields) > 2 or not valid_manifest_key(fields[0]):
            raise SyncError(f"Invalid delivered-items entry: {line}")
        name = fields[0]
        if len(fields) == 1:
            revision = 0
        else:
            try:
                revision = int(fields[1])
            except ValueError as error:
                raise SyncError(f"Invalid delivered revision for {name}: {fields[1]}") from error
            if revision < 0 or str(revision) != fields[1]:
                raise SyncError(f"Invalid delivered revision for {name}: {fields[1]}")
        revisions[name] = max(revisions.get(name, -1), revision)
    return revisions


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
            temporary_path = Path(temporary.name)
        temporary_path.replace(path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def write_manifest(path: Path, revisions: dict[str, int]) -> None:
    content = "".join(f"{name}\t{revisions[name]}\n" for name in sorted(revisions))
    atomic_write_text(path, content)


def deletion_decision(item: RemoteItem, delivered: dict[str, int], local_inbox: Path) -> str | None:
    delivered_revision = delivered.get(item.key)
    if delivered_revision is None or (local_inbox / item.route / item.name).is_dir():
        return None
    return "delete" if item.revision <= delivered_revision else "restore"


def _demote_heading(line: str) -> str:
    """Push one Markdown heading under the item section that now contains it.

    Two levels, because an item sits at `### N — <id>` under a `## <date>`.
    Clamped at six: Markdown has no seventh level, and a deep index must come
    out as a heading Markdown still recognises rather than as literal `#`s.
    """
    match = ATX_HEADING.match(line)
    if not match:
        return line
    level = min(len(match.group(1)) + DIGEST_ITEM_LEVEL - 1, 6)
    return "#" * level + line[match.end(1) :]


def _keep_sections(lines: Sequence[str], headings: Sequence[str]) -> list[str]:
    """Return only the `## <heading>` sections of LINES named in HEADINGS."""
    kept: list[str] = []
    inside = False
    for line in lines:
        if line.startswith("## "):
            inside = line[3:].strip() in headings
        if inside:
            kept.append(line)
    return kept


def _section_body(
    index: str,
    item_name: str,
    *,
    note: str = "",
    sections: Sequence[str] | None = None,
) -> str:
    """Turn one index.md into an inbox section: fenced frontmatter, demoted headings.

    Frontmatter is only unambiguous at the top of a file, so the delimiters become
    a YAML fence here. The fields themselves are copied through untouched — the
    index is the single source of truth and this must not become a second one.

    Relative link destinations are rebased onto the item directory. That is a
    change of vantage point, not of content: `index.md` writes them relative to
    its own directory, and one level up they would resolve to nothing.

    NOTE is this file's own remark about the item rather than part of it, so it
    sits below the fence rather than inside it. SECTIONS narrows the body to the
    named sections, which is how a duplicate capture is collapsed.
    """
    lines = index.splitlines()
    body_start = 0
    if lines and lines[0] == "---":
        closing = next(
            (position for position, line in enumerate(lines[1:], start=1) if line == "---"),
            None,
        )
        if closing is None:
            raise SyncError(f"Unclosed frontmatter in local item: {item_name}")
        lines[0] = "```yaml"
        lines[closing] = "```"
        body_start = closing + 1

    def rewrite(line: str) -> str:
        # The item name is validated against ITEM_NAME, so it carries no regex
        # escapes and can be substituted literally.
        line = _demote_heading(line)
        return MARKDOWN_DESTINATION.sub(rf"]({item_name}/\1)", line)

    body = lines[body_start:]
    if sections is not None:
        # The blank line the dropped sections took with them: a heading has to be
        # separated from whatever now precedes it.
        body = ["", *_keep_sections(body, sections)]
    head = lines[:body_start] + (["", note] if note else [])
    return "\n".join(head + [rewrite(line) for line in body]).strip()


def _received_at(metadata: object, item_name: str) -> datetime:
    if not isinstance(metadata, dict) or not isinstance(metadata.get("received_at"), str):
        raise SyncError(f"Missing received_at for local item: {item_name}")
    try:
        received_at = datetime.fromisoformat(metadata["received_at"])
    except ValueError as error:
        raise SyncError(f"Invalid received_at for local item {item_name}") from error
    if received_at.tzinfo is None:
        raise SyncError(f"received_at must include a timezone for local item: {item_name}")
    return received_at.astimezone(UTC)


def _local_item(item_path: Path) -> tuple[datetime, str, str]:
    name = item_path.name
    if not valid_item_name(name):
        raise SyncError(f"Unexpected local inbox directory: {name}")
    metadata_path = item_path / "metadata.json"
    index_path = item_path / INDEX_NAME
    if not metadata_path.is_file():
        raise SyncError(f"Missing metadata.json for local item: {name}")
    if not (item_path / CAPTURE_DIR / "message.md").is_file():
        raise SyncError(f"Missing {CAPTURE_DIR}/message.md for local item: {name}")
    if not index_path.is_file():
        raise SyncError(f"Missing {INDEX_NAME} for local item: {name}")
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        index = index_path.read_text(encoding="utf-8")
    except (OSError, json.JSONDecodeError) as error:
        raise SyncError(f"Could not read local item {name}: {error}") from error
    return _received_at(metadata, name), name, index


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def _summary(items: list[tuple[datetime, str, str]]) -> str:
    """The two operational numbers: how many are waiting, and how stale the oldest is."""
    summary = _plural(len(items), "item")
    if items:
        age = (datetime.now(UTC) - items[0][0]).days
        summary += f", oldest {_plural(max(age, 0), 'day')}"
    return summary


def _header(items: list[tuple[datetime, str, str]]) -> str:
    return f"# Inbox — {_summary(items)}\n\n{GENERATED_NOTICE}"


def _sorted_items(route_dir: Path) -> list[tuple[datetime, str, str]]:
    """One route's items, oldest first — the ordering both its views number from.

    Called on a route directory, never on the inbox root: from there every entry
    is a route rather than an item, and `_local_item` would reject each one. A
    route directory that does not exist yet is empty, not an error — a route can
    go a long time without receiving anything.
    """
    if not route_dir.is_dir():
        return []
    items = [_local_item(path) for path in sorted(route_dir.iterdir()) if path.is_dir()]
    items.sort(key=lambda item: (item[0], item[1]))
    return items


@dataclass(frozen=True)
class Duplicate:
    """A repeat capture of a link some earlier item in the queue already has."""

    #: The earliest capture of the same link, by directory name.
    of: str
    #: Whether everything this copy would print is already printed under `of`.
    collapse: bool


def duplicate_captures(items: Sequence[tuple[datetime, str, str]]) -> dict[str, Duplicate]:
    """Map each repeat capture to the earliest capture of the same link.

    Saving one page twice is an ordinary accident — read it, get distracted, save
    it again — and two captures of one link produce two items whose Sources, Lead
    and Links are identical, because extraction is cached on the canonical URL.
    Both items stay on disk exactly as captured; only the views collapse them,
    and being derived they are corrected by the next sync if this is ever wrong.

    Identity is the canonical URL alone, which by this point has had its tracking
    parameters stripped, so a link shared once from a share sheet and once by hand
    is one link. Nothing fuzzier: matching note-only items on their text would be
    brittle in exchange for collapsing a two-line item.

    ITEMS must be the oldest-first list both views number from, which is what
    makes the earliest capture the representative and what keeps the two views
    from disagreeing about which copy that is.
    """
    indexes = {name: index for _, name, index in items}
    first: dict[str, str] = {}
    duplicates: dict[str, Duplicate] = {}
    for _, name, index in items:
        fields = _front_matter_fields(index)
        url = fields.get("canonical_url", "")
        # A link list's `canonical_url` is only its top-priority row, so it names
        # one of the item's links rather than the item.
        if not url or fields.get("kind") == "linklist":
            continue
        original = first.setdefault(url, name)
        if original == name:
            continue
        # Collapsing may never hide what the representative does not itself carry.
        # The realistic way that happens is an extraction that failed on the first
        # capture and worked on the second, which would otherwise stub away the
        # only retrieved copy in the queue.
        collapse = _has_sources(indexes[original]) or not _has_sources(index)
        duplicates[name] = Duplicate(original, collapse)
    return duplicates


def _has_sources(index: str) -> bool:
    return "\n## Sources\n" in index


#: The only sections a collapsed duplicate repeats. `## Captured` is the one that
#: can legitimately differ — the same link saved twice with two different notes —
#: and `## Problems` may not be dropped from any view: a failure surfaces in three
#: places — the run log, the dashboard and the item — and all three are meant to
#: keep saying it.
DUPLICATE_SECTIONS = ("Captured", "Problems")


def _duplicate_note(duplicate: Duplicate, positions: dict[str, int]) -> str:
    """Say what this item repeats, what was left out, and what to do about it.

    Addressed to `/route` rather than to the reader, and worded the way
    `neighbours.py`'s block is for the same measured reason
    (`docs/architecture/related-notes.md`): a bare "duplicate of 1" leaves the agent
    to work out whether it still has to open anything.
    """
    where = f"item {positions[duplicate.of]} (`{duplicate.of}`)"
    if duplicate.collapse:
        return (
            f"**Duplicate capture** — the same link as {where}. Its sources, lead and links "
            f"are printed there and are not repeated here; what differs is below. "
            f"Route it once, then drop both directories."
        )
    return (
        f"**Duplicate capture** — the same link as {where}, which retrieved nothing, so this "
        f"copy is printed in full instead. Route it once, then drop both directories."
    )


def render_inbox(route_dir: Path) -> str:
    return _render_digest(_sorted_items(route_dir))


def _render_digest(items: list[tuple[datetime, str, str]]) -> str:
    """Concatenate the items under a heading per day, oldest first.

    The day headings mirror `render_org`'s grouping so the two views describe the
    same shape. They change nothing about how an item is selected: the number is
    still global, positional and identical to the Org view's.

    A repeat capture of a link an earlier item already has keeps its own number
    and its own section, but the section only carries what could differ between
    the two — see `duplicate_captures`.
    """
    duplicates = duplicate_captures(items)
    positions = {name: position for position, (_, name, _) in enumerate(items, 1)}
    sections: list[str] = []
    day = None
    for position, (received_at, name, index) in enumerate(items, 1):
        received_on = received_at.date().isoformat()
        if received_on != day:
            sections.append(f"## {received_on}")
            day = received_on
        duplicate = duplicates.get(name)
        body = _section_body(
            index,
            name,
            note=_duplicate_note(duplicate, positions) if duplicate else "",
            sections=DUPLICATE_SECTIONS if duplicate and duplicate.collapse else None,
        )
        # The number is what the reader selects by and is regenerated on every
        # sync; the id names the directory and outlives the numbering, so a
        # routing decision recorded against "5 — <id>" survives the next run.
        sections.append(
            f"{'#' * DIGEST_ITEM_LEVEL} {position} — {name}\n\n{_nav_line(name)}\n\n{body}"
        )
    content = _header(items)
    if sections:
        content += "\n" + "\n\n".join(sections)
    return content if content.endswith("\n") else content + "\n"


def _nav_line(name: str) -> str:
    return f"[📁 {name}/]({name}/) · [index.md]({name}/{INDEX_NAME})"


def _front_matter_fields(index: str) -> dict[str, str]:
    """Read the index's frontmatter scalars.

    `index.py` writes flat `key: value` lines and nothing else, so this stays a
    reader for that shape rather than a YAML dependency the laptop side would
    otherwise not need.
    """
    lines = index.splitlines()
    if not lines or lines[0] != "---":
        return {}
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line == "---":
            break
        key, separator, value = line.partition(":")
        if separator and key and not key.startswith(" "):
            fields[key.strip()] = value.strip().strip('"')
    return fields


def _org_text(value: str, limit: int = 0) -> str:
    """Flatten arbitrary extracted text for a heading or a property value.

    This is the only place extracted text reaches Org, and Org gives `*`, `[[`
    and newlines structural meaning. Keeping it to one collapsed line with the
    link brackets broken is why the item bodies stay Markdown.
    """
    flattened = " ".join(value.split()).replace("[[", "[ [")
    if limit and len(flattened) > limit:
        flattened = flattened[: limit - 1].rstrip() + "…"
    return flattened


def _index_section(index: str, heading: str) -> list[str]:
    """Return the lines of one `## <heading>` section of an index."""
    collected: list[str] = []
    inside = False
    for line in index.splitlines():
        if line.startswith("## "):
            if inside:
                break
            inside = line[3:].strip() == heading
        elif inside:
            collected.append(line)
    return collected


def _quoted_lines(lines: Sequence[str]) -> Iterator[str]:
    """Yield the blockquote content of LINES, unquoted."""
    for line in lines:
        text = line.removeprefix(">").strip()
        if text:
            yield text


def _org_link(target: str, label: str) -> str:
    """Return an Org link, or the label alone when TARGET cannot be one.

    A bracket in the target would close the link early and swallow the rest of
    the line, which in a generated file means the line after it too.
    """
    return f"[[{target}][{label}]]" if target and not set("[]") & set(target) else ""


def _org_link_description(text: str) -> str:
    """Return TEXT safe to stand as a link's description.

    A `]` in an extracted title would close the description early and leave the
    rest of the heading as loose text; `_org_text`'s `[[` guard is about a link
    *starting* mid-heading and does not cover it. Substituted rather than
    dropped, because the title is the only thing naming the item.
    """
    return text.replace("[", "(").replace("]", ")")


def _org_tags(*values: str) -> str:
    """Return VALUES as one trailing Org tag string, or "" when nothing is left.

    Org tags admit only `[[:alnum:]_@#%]`, and `kind` comes from an extractor
    rather than from a fixed list, so anything else becomes `_` instead of
    producing a heading whose tag Org does not read as one. Empty values are
    dropped, so a caller can pass a tag it may or may not have.
    """
    tags = [
        tag
        for tag in (ORG_TAG_UNSAFE.sub("_", value.strip()).strip("_") for value in values)
        if tag
    ]
    return f"  :{':'.join(tags)}:" if tags else ""


def _org_italic(text: str) -> str:
    """Italicise TEXT, unless it carries markers of its own that would fight it."""
    return f"/{text}/" if text and not set("/*_") & set(text) else text


def render_org(items: list[tuple[datetime, str, str]]) -> str:
    """Render the Emacs navigation view: a heading per day, a subheading per item.

    Navigation only — no extracted text is embedded beyond a one-line label, so
    little here has to be escaped and `index.md` never has to become Org. It
    carries no state either: deleting the item directory remains the signal that
    an item was processed, and a mark written here would be lost next sync.

    There is deliberately no property drawer. Everything one held is either in
    the heading or one link away, and eight lines of restatement per item is
    what stopped two dozen items fitting on a screen.

    Grouping by day is the same economy carried further: the date was printed on
    every line to be read once per group, and once the items sit under it they no
    longer need blank lines between them to be told apart. The item's label *is*
    the link to its index, so the line that used to carry a third link carries
    two. Numbering stays global and positional across the groups — it is the one
    interface with `triage.md`, and a per-day numbering would break it.

    The link line's shape is depended on: Emacs reads the item's directory back
    out of `[[file:<id>/][directory]]` to know what a drop should delete, since
    that is now the only place the id appears.

    `showall` rather than `overview`: with two levels, `overview` shows the days
    and hides every item under them, which is the file with its contents removed.

    A repeat capture keeps its own number and its own line — folding two captures
    into one heading would make the numbering non-injective, and the number is what
    Emacs finds an item by. It is marked with a `dup` tag and told which item it
    repeats, and `triage.md` is where what that means is spelled out.
    """
    duplicates = duplicate_captures(items)
    positions = {name: position for position, (_, name, _) in enumerate(items, 1)}
    lines = [
        "#+TITLE: Info triage inbox",
        f"#+SUBTITLE: {_summary(items)} — generated by sync.sh, do not edit",
        "#+STARTUP: showall",
        ORG_AGENT_NOTICE,
    ]
    day = None
    for position, (received_at, name, index) in enumerate(items, 1):
        # Items are sorted by `received_at`, so equal dates are always adjacent
        # and a group can be closed the moment the date changes.
        received_on = received_at.date().isoformat()
        if received_on != day:
            lines.extend(["", f"* {received_on}", ""])
            day = received_on
        fields = _front_matter_fields(index)
        intent = fields.get("intent", "")
        if intent == "null":
            intent = ""
        label = fields.get("title") or fields.get("headline") or intent
        title = _org_link_description(_org_text(label, limit=80)) or "(untitled)"
        # The title is the link, so the index needs no separate one. Falling back
        # to the bare title keeps an item named even if the link cannot be made.
        heading = _org_link(f"file:{name}/{INDEX_NAME}", title) or title
        # The kind is a tag rather than a column: Org right-aligns it, which
        # gives every title the same left edge and the full width to run to.
        kind = fields.get("kind", "")
        duplicate = duplicates.get(name)
        tag = _org_tags(kind if kind != "null" else "", "dup" if duplicate else "")
        lines.append(f"** {position} · {heading}{tag}")
        # The user's own words about why he kept it, when they are not already
        # the label — the one thing the heading cannot carry and nothing else has.
        if intent and intent != label:
            lines.append(f"   {_org_italic(_org_text(intent, limit=90))}")
        # The directory link stays first on this line: Emacs reads the item's own
        # directory back out of the first one it finds after the heading.
        trail = [
            _org_link(f"file:{name}/", "directory"),
            _org_link(fields.get("canonical_url", ""), "source"),
        ]
        if duplicate:
            trail.append(f"dup of {positions[duplicate.of]}")
        lines.append("   " + " · ".join(part for part in trail if part))
    return "\n".join(lines) + "\n"


def generate_inbox(local_inbox: Path) -> None:
    """Rebuild both views for every route.

    Each route is a self-contained queue: its own two files, its own 1..N. A route
    is a directory of the inbox: the download brings one over for every route the
    server has, empty ones included, so a route with nothing in it still gets both
    files. An absent `triage.org` could not be told apart from a sync that did not
    run.
    """
    local_inbox.mkdir(parents=True, exist_ok=True)
    for route in route_directories(local_inbox, strict=False):
        route_dir = local_inbox / route
        # Both views are rendered before either is written, so a failure in one
        # cannot leave the two disagreeing about what is in the inbox.
        items = _sorted_items(route_dir)
        digest = _render_digest(items)
        org = render_org(items)
        atomic_write_text(route_dir / DIGEST_NAME, digest)
        atomic_write_text(route_dir / ORG_NAME, org)


def neighbour_query(index: str) -> str:
    """What one item is about, in the words its own index uses.

    Title, the user's intent and the opening of the Lead — the query the retrieval was
    measured against. A short-form Lead's stream labels (`**Caption**`) are dropped:
    they say where the text came from, not what it is about.
    """
    fields = _front_matter_fields(index)
    lead_lines = _index_section(index, "Lead") or _index_section(index, "Captured")
    lead = " ".join(
        text
        for text in _quoted_lines(lead_lines)
        if not (text.startswith("**") and text.endswith("**"))
    )
    parts = (
        fields.get("title") or fields.get("headline") or "",
        fields.get("intent", ""),
        " ".join(lead.split()[:NEIGHBOUR_LEAD_WORDS]),
    )
    return ". ".join(part for part in parts if part and part != "null")


def _neighbours_module():
    """Import the annotator lazily.

    Keeps this file free of third-party imports, so `--regenerate` costs nothing and a
    laptop without the optional extra still synchronizes.
    """
    from info_triage import neighbours

    return neighbours


def _progress(label: str, done: int, total: int) -> None:
    """Report the annotation pass: one rewritten line on a terminal, one line per item
    when the output is piped or run from Emacs."""
    if not total:
        print(f"    {label}", flush=True)
        return
    line = f"    [{done:>{len(str(total))}}/{total}] {label}"
    if sys.stdout.isatty():
        print(f"\r{line}\033[K", end="", flush=True)
        if done == total:
            print()
    else:
        print(line, flush=True)


def _write_blocks(route_dir: Path, blocks: dict[str, str], apply_block: Callable) -> int:
    """Put each item's block into its own index.md. Returns how many were written.

    An item that is no longer here was processed while this ran, which is the whole
    point of running it late. It is logged and skipped: `atomic_write_text` creates
    parents, and would otherwise resurrect the directory the user just dropped as an
    item holding nothing but an index.
    """
    written = 0
    for name in sorted(blocks):
        index_path = route_dir / name / INDEX_NAME
        if not (route_dir / name).is_dir() or not index_path.is_file():
            print(f"Item is no longer here, leaving it: {route_dir.name}/{name}")
            continue
        try:
            index = index_path.read_text(encoding="utf-8")
        except OSError as error:
            print(f"Could not re-read {route_dir.name}/{name}: {error}")
            continue
        atomic_write_text(index_path, apply_block(index, blocks[name]))
        written += 1
    return written


def annotate_inbox(config: SyncConfig) -> None:
    """Add each item's possible-neighbours section on one route, once the queue is usable.

    This deliberately runs last, after both views are on disk and the items have been
    announced as ready. It costs about a minute, and it is for the agent rather than
    for the reader, who is already working the queue by the time it starts. So every
    index it needs is read into memory before the slow part begins, and every write is
    conditional on the item still being there.

    Enrichment, like everything after capture: nothing here may fail a sync.
    """
    route_dir = config.local_inbox / config.neighbour_route
    if not config.annotate or not route_dir.is_dir():
        return
    if config.org_root is None or config.obsidian_root is None:
        return
    for root in (config.org_root, config.obsidian_root):
        if not root.is_dir():
            print(f"Possible neighbours skipped: no notes at {root}")
            return
    try:
        neighbours = _neighbours_module()
    except ImportError:
        print("Possible neighbours skipped: run 'uv sync --extra neighbours' to enable them")
        return

    # A collapsed duplicate's block would be written into an index whose neighbours
    # section `triage.md` does not print, so the pass would spend a second per item
    # on nothing. Defensive against a half-deleted item: annotating everything is
    # the safe answer, and this may not fail a sync.
    try:
        collapsed = {
            name
            for name, duplicate in duplicate_captures(_sorted_items(route_dir)).items()
            if duplicate.collapse
        }
    except SyncError:
        collapsed = set()

    # Read first, compute second, write third. Nothing below this loop reads an item
    # again except to write it, so the user is free to work the queue meanwhile.
    queries: list[tuple[str, str]] = []
    for item in sorted(path for path in route_dir.iterdir() if path.is_dir()):
        if item.name in collapsed:
            continue
        try:
            index = (item / INDEX_NAME).read_text(encoding="utf-8")
        except OSError as error:
            print(f"Could not read {route_dir.name}/{item.name}: {error}")
            continue
        queries.append((item.name, neighbour_query(index)))
    if not queries:
        return

    print(
        f"==> Looking for possible neighbours of {_plural(len(queries), 'item')} — "
        "the queue above is ready now; this only adds a section for the agent"
    )
    started = time.monotonic()
    try:
        blocks = neighbours.annotate(
            queries,
            config.org_root,
            config.obsidian_root,
            org_exclude=config.org_exclude,
            progress=_progress,
        )
        written = _write_blocks(route_dir, blocks, neighbours.apply_block)
        if written:
            # Rendered from disk immediately before the write, not from what was read
            # above: dropping an item regenerates both views, so this must reflect
            # whatever is there now to stay numbered like the `triage.org` beside it.
            atomic_write_text(route_dir / DIGEST_NAME, _render_digest(_sorted_items(route_dir)))
    except Exception as error:  # noqa: BLE001 - enrichment may never fail a sync
        print(f"Possible neighbours skipped: {type(error).__name__}: {error}")
        return
    elapsed = f"{time.monotonic() - started:.0f}s"
    if written:
        print(f"==> Neighbours added to {written} of {len(queries)} items in {elapsed}")
        print(f"Rebuilt with them: {route_dir / DIGEST_NAME}")
    else:
        print(f"==> No possible neighbours cleared the threshold ({elapsed})")


def _remove_stale_local_items(
    config: SyncConfig, remote_items: list[RemoteItem], delivered: dict[str, int]
) -> None:
    """Drop laptop copies of items the server no longer has under that name.

    A hashtag edit moves an item between routes by renaming its directory on the
    server, so the old copy is gone before this runs and `deletion_decision` never
    sees it. The download is deliberately without `--delete` — that is what makes
    deleting an item locally mean "processed" — so without this pass the old copy
    would stay in its former route's views forever.

    Still present locally is the discriminator: an item the laptop itself deleted
    is not here, and must not be resurrected as a deletion notice.
    """
    remote_keys = {item.key for item in remote_items}
    if delivered and not remote_keys:
        raise SyncError(
            "The server inbox listed no items while items are recorded as delivered.\n"
            "Refusing to remove local copies because the listing may have failed."
        )
    stale = sorted(
        key for key in set(delivered) - remote_keys if (config.local_inbox / key).is_dir()
    )
    if stale:
        print("==> Removing local copies the server no longer has")
    for key in stale:
        shutil.rmtree(config.local_inbox / key)
        delivered.pop(key, None)
        print(f"Removed stale local item: {key}")
    write_manifest(config.manifest, delivered)


def synchronize(config: SyncConfig, command_runner: CommandRunner = run_command) -> None:
    manifest_existed = config.manifest.exists()
    if manifest_existed and not config.local_inbox.is_dir():
        raise SyncError(
            f"Local inbox is missing: {config.local_inbox}\n"
            "Refusing to synchronize because its contents may have been deleted accidentally."
        )

    config.local_inbox.mkdir(parents=True, exist_ok=True)
    config.state_dir.mkdir(parents=True, exist_ok=True)
    if not config.manifest.exists():
        atomic_write_text(config.manifest, "")

    with tempfile.TemporaryDirectory() as temporary:
        remote_metadata = Path(temporary) / "remote-metadata"
        remote_metadata.mkdir()

        print("==> Reading server item revisions")
        command_runner(config.remote_command(f"test -d {shlex.quote(config.remote_inbox)}"))
        command_runner(
            [
                "rsync",
                "-az",
                # Two levels now: route directories, then item directories. rsync
                # tests each path component in rule order, so both directory
                # includes have to precede the file include.
                "--include",
                "/*/",
                "--include",
                "/*/*/",
                "--include",
                "/*/*/metadata.json",
                "--exclude",
                "*",
                f"{config.remote_location}/",
                f"{remote_metadata}/",
            ]
        )
        remote_items = read_remote_items(remote_metadata)
        delivered = read_manifest(config.manifest)
        write_manifest(config.manifest, delivered)

        print("==> Removing items processed on the laptop")
        for item in remote_items:
            decision = deletion_decision(item, delivered, config.local_inbox)
            if decision == "delete":
                remote_path = f"{config.remote_inbox}/{item.key}"
                command_runner(config.remote_command(f"rm -rf -- {shlex.quote(remote_path)}"))
                print(f"Removed processed item: {item.key} revision {item.revision}")
            elif decision == "restore":
                print(f"Restoring updated item: {item.key} revision {item.revision}")

        _remove_stale_local_items(config, remote_items, delivered)

        print("==> Downloading new and edited items")
        command_runner(
            [
                "rsync",
                "-azc",
                f"{config.remote_location}/",
                f"{config.local_inbox}/",
            ]
        )

    for item in remote_items:
        delivered[item.key] = max(delivered.get(item.key, -1), item.revision)
    write_manifest(config.manifest, delivered)
    generate_inbox(config.local_inbox)

    # Everything the laptop was owed is on disk here. What follows is enrichment for
    # the agent, and the queue is meant to be read while it runs.
    print("==> Synchronization complete — the inbox is ready to review now")
    print(f"Laptop inbox: {config.local_inbox}")
    annotate_inbox(config)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="sync.sh",
        description="Synchronize the server's inbox onto this machine and regenerate its views.",
    )
    parser.add_argument(
        "--regenerate",
        action="store_true",
        help=(
            "Rewrite triage.md and triage.org from the item directories already here, "
            "without touching the server. Run this after removing an item locally: both "
            "views renumber together, so the numbers you quote to /route still agree."
        ),
    )
    parser.add_argument(
        "--no-neighbours",
        dest="neighbours",
        action="store_false",
        default=None,
        help=(
            "Skip the possible-neighbours pass that runs after the items are delivered. "
            "The sync itself is unaffected either way."
        ),
    )
    parser.add_argument(
        "--neighbours",
        dest="neighbours",
        action="store_true",
        help=(
            "Recompute possible neighbours during --regenerate. Without it a regenerate "
            "reuses the sections already in the item directories, which is what makes it "
            "instant; pass this when the plans or the vault have moved since the sync."
        ),
    )
    arguments = parser.parse_args(argv)
    load_env_file()
    try:
        config = default_config()
        if arguments.regenerate:
            generate_inbox(config.local_inbox)
            print(f"==> Regenerated {DIGEST_NAME} and {ORG_NAME} in {config.local_inbox}")
            if arguments.neighbours:
                annotate_inbox(config)
        else:
            synchronize(replace(config, annotate=arguments.neighbours is not False))
    except (SyncError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
